name: Has Changes
on:
  push:

permissions:
  contents: read

jobs:
  has-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 'lts/*'
      - run: npm ci --ignore-scripts
      - run: npm run preparesite
      - name: Check if there are changes
        id: changes
        run: git diff --quiet --exit-code
