name: Has Changes
on:
  push:

permissions:
  contents: read

jobs:
  has-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 'lts/*'
      - run: npm ci --ignore-scripts
      - run: npm run preparesite
      - name: Check if there are changes
        id: changes
        run: git diff --quiet --exit-code
