name: test-node-12
on:
  push:

concurrency:
  group: test-node-12-branch-node-${{ github.ref }}
  cancel-in-progress: true

# TODO : delete this workflow on next major if we drop node 12, 14 and 16

jobs:
  test-node-12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: NPM_CONFIG_ENGINE_STRICT=false npm ci --ignore-scripts
      - run: npm run test:json
